# Generated by Django 5.0.6 on 2024-08-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_driver_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegCont',
            new_name='Registro_Contabilidad',
        ),
    ]
