# Generated by Django 5.0.6 on 2024-08-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_driver_admin', '0002_rename_regcont_registro_contabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
