# Generated by Django 5.0.6 on 2024-08-07 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_driver_admin', '0003_alter_chofer_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='creacion_registro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
