# Generated by Django 5.0.6 on 2024-08-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_driver_admin', '0004_alter_chofer_creacion_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='creacion_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
